logging:
  level: "DEBUG"

llm:
  provider: "google_genai_studio"

  google_genai:
    model: "gemini-2.5-flash"
    api_key: "AIzaSyAUQhDu4_Y8wLjmFXN9gWhlDCJ3-Dey4-s" # Replace with your actual key

  openai:
    model: "Gemini-2.0-Flash-Preview"
    api_key: "kQMgOqm4E1QF80V3UZY_Yqiu-w3pEi_k7P_KV19m8oY" # Replace with your actual key
    base_url: "https://api.poe.com/v1" # Optional, for proxy
context_management:
  max_history_items: 6
  max_tool_output_tokens: 2500
# Configure the browser adapter to use browsermcp
browser:
  adapter: "playwright"
  playwright:
    cdp_endpoint: "http://localhost:9222"
opa:
  provider: "noop" # Can be "http" or "noop"
  url: "http://localhost:8181/v1/data/aegis/allow"

# OmniParser "Eyes" config
omni_parser_adapter:
  script_path: "scripts/omni_parser.test.py"
  workdir: "scripts/workdir" # Directory where models and outputs are stored


