name: "Virtual Influencer Base Character Sheet V2 (Full)"
description: "Generates the complete base set of character images using an efficient, two-routine pattern."
persona: "You are an AI agent that uses web tools to generate creative content."

routines:
  generate_first_image_with_reference:
    - name: "Paste Reference Image for {{params.description}}"
      type: "agent_step"
      prompt: 'Use the `paste_image` tool with selector `div.ql-editor[role="textbox"]`'
    - name: "Set Prompt for {{params.description}}"
      type: "agent_step"
      prompt: 'Use the `type_text` tool with selector `div.ql-editor[role="textbox"]` to enter the prompt: "{{params.prompt_text}}"'
    - name: "Click Send"
      type: "agent_step"
      prompt: 'Use the `click` tool with selector `button[aria-label="Send message"]`'
    - name: "Wait for Generation"
      type: "agent_step"
      prompt: "wait for 60 seconds"

  generate_subsequent_image:
    - name: "Set Prompt for {{params.description}}"
      type: "agent_step"
      prompt: 'Use the `type_text` tool with selector `div.ql-editor[role="textbox"]` to enter the prompt: "{{params.prompt_text}}"'
    - name: "Click Send"
      type: "agent_step"
      prompt: 'Use the `click` tool with selector `button[aria-label="Send message"]`'
    - name: "Wait for Generation"
      type: "agent_step"
      prompt: "wait for 60 seconds"

steps:
  - name: "Navigate to Image Generator"
    type: "agent_step"
    prompt: "Navigate to https://gemini.google.com/u/2/app"

  # --- Task 1: Straight Profile Headshots ---
  - name: "Task 1 - Generate Images"
    type: "run_routine"
    routine_name: "generate_first_image_with_reference"
    loop_with:
      - description: "Casual Look"
        prompt_text: "Change attire to a t-shirt and jeans. Change background to home. Set evening light."
      - description: "Party Look"
        prompt_text: "Change attire to party wear. Set home dimlit. Make her waving."
  - name: "Human Verification 1"
    type: "human_intervention"
    prompt: "Please verify the two generated headshot images (Casual, Party)."

  # --- Task 2: Side Profile Shots with Different Emotions ---
  - name: "Task 2 - Generate First Image (Annoyed)"
    type: "run_routine"
    routine_name: "generate_first_image_with_reference"
    loop_with:
      - description: "Annoyed Emotion"
        prompt_text: "Change to frontal view profile head shot. Change background to a park. Make her look annoyed."
  - name: "Task 2 - Generate Subsequent Images (Sad, Amused)"
    type: "run_routine"
    routine_name: "generate_subsequent_image"
    loop_with:
      - description: "Sad Emotion"
        prompt_text: "Change to frontal view profile head shot. Make her look sad."
      - description: "Amused Emotion"
        prompt_text: "Change to frontal view profile head shot. Change background to a park. Make her look amused."
  - name: "Human Verification 2"
    type: "human_intervention"
    prompt: "Please verify the three generated emotion images (Annoyed, Sad, Amused)."

  # --- Task 3: Full Length Poses (Yoga and Office) ---
  - name: "Task 3 - Generate First Image (Yoga)"
    type: "run_routine"
    routine_name: "generate_first_image_with_reference"
    loop_with:
      - description: "Yoga Pose"
        prompt_text: "Make it a dynamic yoga pose. Change background to home. Make her smiling."
  - name: "Task 3 - Generate Subsequent Image (Office)"
    type: "run_routine"
    routine_name: "generate_subsequent_image"
    loop_with:
      - description: "Office Pose"
        prompt_text: "Change attire to formal wear. Change background to an office. Make her shrugging."
  - name: "Human Verification 3"
    type: "human_intervention"
    prompt: "Please verify the two generated full-length poses (Yoga, Office)."

  # --- Task 4: Back Profile and Waist Length Shots ---
  - name: "Task 4 - Generate First Image (Crying)"
    type: "run_routine"
    routine_name: "generate_first_image_with_reference"
    loop_with:
      - description: "Crying Emotion"
        prompt_text: "Show a crying emotion. Change background to a park."
  - name: "Task 4 - Generate Subsequent Images (Saree, Kurta)"
    type: "run_routine"
    routine_name: "generate_subsequent_image"
    loop_with:
      - description: "Happy in Saree"
        prompt_text: "Make it a waist length shot. Change attire to a saree. Change background to a park. Show a happy emotion. Make her standing."
      - description: "Sitting in Kurta"
        prompt_text: "Change attire to a kurta. Change background to a cafe. Make her sitting."
  - name: "Human Verification 4"
    type: "human_intervention"
    prompt: "Please verify the final three images (Crying, Saree, Kurta)."